name: Ijakhdem
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  get_it:
  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  dartz:
  http:
  data_connection_checker:
  mercury_client: 1.1.12
  shared_preferences:
  device_preview:
  flutter_zoom_drawer: ^1.0.4+1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/
    - Assets/Fonts/

  # fonts:
  #   - family: SourceSansPro
  #     fonts:
  #       - asset: Assets/Fonts/SourceSansPro-Black.ttf
  #         weight: 900
  #       - asset: Assets/Fonts/SourceSansPro-Bold.ttf
  #         weight: 700
  #       - asset: Assets/Fonts/SourceSansPro-ExtraLight.ttf
  #         weight: 100
  #       - asset: Assets/Fonts/SourceSansPro-Light.ttf
  #         weight: 300
  #       - asset: Assets/Fonts/SourceSansPro-Regular.ttf
  #       - asset: Assets/Fonts/SourceSansPro-SemiBold.ttf
  #         weight: 600

  #   - family: SFProDisplay
  #     fonts:
  #       - asset: Assets/Fonts/SFProDisplay-Semibold.ttf
  #       - asset: Assets/Fonts/SFProText-Light.ttf
  #         weight: 600
